---
- name: Install clockhouse server dependencies
  ansible.builtin.apt:
    name:
      - clickhouse-server
      - clickhouse-client
    state: present
    update_cache: no

- name: Start clickhouse service
  ansible.builtin.systemd:
    enabled: yes
    name: clickhouse-server
    state: started
